version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ
      - "15672:15672" # Management Plugin
    #environment:
      #RABBITMQ_DEFAULT_USER: user
      #RABBITMQ_DEFAULT_PASS: password
      #RABBITMQ_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      #- ./rabbitmq/init-rabbitmq.sh:/docker-entrypoint-init.d/init-rabbitmq.sh
    entrypoint: ["docker-entrypoint.sh"]
    command: ["rabbitmq-server"]
    networks:
      - rabbitmq_network

  entry_generator:
    build:
      context: ./generator/
      dockerfile: Dockerfile
    container_name: entrygenerator
    depends_on:
      - rabbitmq
      - redis
    environment:
      - LOG_LEVEL=DEBUG
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - GENERATOR_MODE=entry
      - REDIS_PASSWORD=your_redis_password
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
    networks:
      - rabbitmq_network

  exit_generator:
    build:
      context: ./generator/
      dockerfile: Dockerfile
    container_name: exitgenerator
    depends_on:
      - rabbitmq
      - redis
    environment:
      - LOG_LEVEL=DEBUG
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - GENERATOR_MODE=exit
      - REDIS_PASSWORD=your_redis_password
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
    networks:
      - rabbitmq_network

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      - REDIS_PASSWORD=your_redis_password # Set Redis password
    networks:
      - rabbitmq_network

networks:
  # redis_network:
  #   driver: bridge
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_logs:
