FROM golang:1.23.1 as builder

WORKDIR /app

COPY go.mod go.sum ./

# Download all dependencies. They will be cached if the go.mod and go.sum files are not changed
RUN go mod download

COPY . .

# RUN CGO_ENABLED=0 GOOS=linux go build -o app .

# # Step 2: Create a smaller image for running the app
# FROM alpine:latest  

# WORKDIR /root/

# # Copy the pre-built binary file from the builder stage
# COPY --from=builder /app/app .

# # Command to run the executable
# CMD ["./app"]
