global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # - job_name: 'api_metrics'
  #   static_configs:
  #     - targets: ['python-server:8000']  

  - job_name: 'go_consumer_metrics'
    static_configs:
      - targets: ['record-keeper:2112']  